version: "3"

services:
  frontend:
    image: thejashari/frontend-app
    ports:
      - "3001:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:3333

  backend:
    image: thejashari/backend-app
    networks:
      database_net:
        ipv4_address: 172.16.238.11
    ports:
      - "3333:3333"
    depends_on:
      - mongo
    environment:
      MONGODB_URI: mongodb://172.16.238.12:27017/my_database

  mongo:
    image: mongo
    networks:
      database_net:
        ipv4_address: 172.16.238.12
    ports:
      - "27017:27017"
    volumes:
      - db-data:/data/db
volumes:
  db-data:

networks:
  database_net:
    driver: bridge
    ipam:
      config:
        - subnet: "172.16.238.0/24"
      driver: default
